dist: trusty
language: ruby
rvm:
  - 2.3
  - 2.4
script:
  - RAILS_ENV=test bundle exec rake db:setup
  - RAILS_ENV=test bundle exec rake spec
services:
  - postgresql
addons:
  - postgresql: "9.6"
before_script:
  - psql -c 'create database sharebrew_test;' -U postgres
  - cp config/database.yml.travis config/database.yml
