version: '3'
services:
  db:
    image: postgres:9.6.2
    volumes:
      - share-brew-pgdata:/var/lib/postgresql/data
  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/srv/share-brew
    ports:
      - "3000:3000"
    depends_on:
      - db
volumes:
  share-brew-pgdata:
