development: &default
  adapter: postgresql
  encoding: unicode
  database: sharebrew_development
  timeout: 5000
  pool: 5
  username: postgres
  password:
  host: db

test:
  <<: *default
  database: sharebrew_test

production:
  <<: *default
  database: sharebrew_production
